import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:printing/printing.dart';
import 'package:provider/provider.dart';
import '../../config/theme.dart';
import '../../models/stundenzettel_model.dart';
import '../../providers/auth_provider.dart';
import '../../services/supabase_service.dart';
import '../../services/pdf_service.dart';
import '../../widgets/gold_button.dart';
import '../../widgets/signature_pad_dialog.dart';

class StundenzettelDetailScreen extends StatefulWidget {
  final StundenzettelModel sz;

  const StundenzettelDetailScreen({super.key, required this.sz});

  @override
  State<StundenzettelDetailScreen> createState() =>
      _StundenzettelDetailScreenState();
}

class _StundenzettelDetailScreenState
    extends State<StundenzettelDetailScreen> {
  late StundenzettelModel _sz;
  bool _isLoading = true;
  bool _isSigning = false;
  bool _isGeneratingPdf = false;

  @override
  void initState() {
    super.initState();
    _sz = widget.sz;
    _loadFresh();
  }

  Future<void> _loadFresh() async {
    setState(() => _isLoading = true);
    try {
      final fresh = await SupabaseService.getStundenzettelById(widget.sz.id);
      if (mounted) {
        setState(() {
          if (fresh != null) _sz = fresh;
          _isLoading = false;
        });
      }
    } catch (_) {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  String get _employeeName => _sz.employeeName ?? 'Unbekannt';

  Future<void> _signAdmin() async {
    final signature = await SignaturePadDialog.show(
      context,
      title: 'Admin-Unterschrift',
    );
    if (signature == null || !mounted) return;

    setState(() => _isSigning = true);
    try {
      await SupabaseService.signStundenzettelAdmin(
          id: _sz.id, signature: signature);
      await _loadFresh();
      if (_sz.isFullySigned && mounted) {
        // PDF will be available in the employee's document folder automatically 
        // since the employee usually signs last and it auto-generates.
        // If admin signs last, we could auto-generate here, but we will rely 
        // on the backend or manual preview for now to prevent duplication.
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Fehler beim Unterschreiben: ${e.toString()}'),
            backgroundColor: AppTheme.errorBg,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isSigning = false);
    }
  }

  // PDF is auto-generated by the employee when they sign.
  // The admin can only preview it via the top right icon.

  Future<void> _previewPdf() async {
    try {
      final pdfBytes =
          await PdfService.generateStundenzettel(_sz, _employeeName);
      await Printing.layoutPdf(onLayout: (_) async => pdfBytes);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Fehler: ${e.toString()}')),
        );
      }
    }
  }

  Color get _statusColor {
    switch (_sz.status) {
      case StundenzettelStatus.draft:
        return AppTheme.warning;
      case StundenzettelStatus.adminSigned:
        return AppTheme.info;
      case StundenzettelStatus.completed:
        return AppTheme.success;
    }
  }

  Color get _statusBgColor {
    switch (_sz.status) {
      case StundenzettelStatus.draft:
        return AppTheme.warningBg;
      case StundenzettelStatus.adminSigned:
        return AppTheme.infoBg;
      case StundenzettelStatus.completed:
        return AppTheme.successBg;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.bgDark,
      appBar: AppBar(
        title: const Text('Stundenzettel'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_rounded),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          if (_sz.status == StundenzettelStatus.completed)
            IconButton(
              icon: const Icon(Icons.picture_as_pdf_rounded,
                  color: AppTheme.goldPrimary),
              onPressed: _previewPdf,
              tooltip: 'PDF Vorschau',
            ),
        ],
      ),
      body: _isLoading
          ? const Center(
              child: CircularProgressIndicator(color: AppTheme.goldPrimary),
            )
          : SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _buildHeaderCard(),
                  const SizedBox(height: 16),
                  _buildStatsRow(),
                  const SizedBox(height: 16),
                  _buildSectionTitle('Arbeitsstunden'),
                  const SizedBox(height: 10),
                  _buildWorkEntriesTable(),
                  const SizedBox(height: 20),
                  _buildSectionTitle('Unterschriften'),
                  const SizedBox(height: 10),
                  _buildSignaturesRow(),
                  if (_sz.isFullySigned) ...[
                    const SizedBox(height: 16),
                    Container(
                      width: double.infinity,
                      padding: const EdgeInsets.all(16),
                      decoration: BoxDecoration(
                        color: AppTheme.successBg,
                        borderRadius: BorderRadius.circular(14),
                        border: Border.all(color: AppTheme.success.withOpacity(0.4)),
                      ),
                      child: const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Icon(Icons.check_circle_rounded,
                              color: AppTheme.success, size: 22),
                          SizedBox(width: 8),
                          Text(
                            'Vollständig unterzeichnet!',
                            style: TextStyle(
                              color: AppTheme.success,
                              fontSize: 15,
                              fontWeight: FontWeight.w700,
                            ),
                          ),
                        ],
                      ),
                    ),
                  ],
                  const SizedBox(height: 32),
                ],
              ),
            ),
    );
  }

  Widget _buildHeaderCard() {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppTheme.bgCard,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(color: AppTheme.borderGold),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            _employeeName,
            style: const TextStyle(
              color: AppTheme.textPrimary,
              fontSize: 22,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 6),
          Text(
            _sz.monthYearLabel,
            style: const TextStyle(
              color: AppTheme.textGold,
              fontSize: 16,
              fontWeight: FontWeight.w500,
            ),
          ),
          const SizedBox(height: 12),
          Container(
            padding:
                const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
            decoration: BoxDecoration(
              color: _statusBgColor,
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: _statusColor.withOpacity(0.5)),
            ),
            child: Text(
              _sz.status.label,
              style: TextStyle(
                color: _statusColor,
                fontSize: 13,
                fontWeight: FontWeight.w600,
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildStatsRow() {
    return Row(
      children: [
        Expanded(
          child: _goldStatBox(
            Icons.calendar_today_rounded,
            '${_sz.totalDays ?? 0}',
            'Arbeitstage',
          ),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: _goldStatBox(
            Icons.access_time_rounded,
            ((_sz.totalHours ?? 0)).toStringAsFixed(1),
            'Gesamtstunden',
          ),
        ),
      ],
    );
  }

  Widget _goldStatBox(IconData icon, String value, String label) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        gradient: AppTheme.goldGradientSubtle,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppTheme.borderGold),
      ),
      child: Column(
        children: [
          Icon(icon, color: AppTheme.goldPrimary, size: 22),
          const SizedBox(height: 6),
          Text(
            value,
            style: const TextStyle(
              color: AppTheme.textGold,
              fontSize: 24,
              fontWeight: FontWeight.w700,
            ),
          ),
          const SizedBox(height: 2),
          Text(
            label,
            style: const TextStyle(
                color: AppTheme.textSecondary, fontSize: 12),
          ),
        ],
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Row(
      children: [
        Container(
          width: 4,
          height: 20,
          decoration: BoxDecoration(
            gradient: AppTheme.goldGradient,
            borderRadius: BorderRadius.circular(2),
          ),
        ),
        const SizedBox(width: 10),
        Text(
          title,
          style: const TextStyle(
            color: AppTheme.textPrimary,
            fontSize: 16,
            fontWeight: FontWeight.w700,
          ),
        ),
      ],
    );
  }

  Widget _buildWorkEntriesTable() {
    if (_sz.workEntries.isEmpty) {
      return Container(
        width: double.infinity,
        padding: const EdgeInsets.all(20),
        decoration: BoxDecoration(
          color: AppTheme.bgCard,
          borderRadius: BorderRadius.circular(14),
          border: Border.all(color: AppTheme.border),
        ),
        child: const Center(
          child: Text(
            'Keine Einträge',
            style:
                TextStyle(color: AppTheme.textMuted, fontSize: 14),
          ),
        ),
      );
    }

    final dateFormat = DateFormat('dd.MM.yyyy');

    return Container(
      decoration: BoxDecoration(
        color: AppTheme.bgCard,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppTheme.border),
      ),
      child: SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: DataTable(
          headingRowColor: WidgetStateProperty.all(AppTheme.bgCardElevated),
          dataRowColor: WidgetStateProperty.resolveWith((states) {
            return AppTheme.bgCard;
          }),
          headingTextStyle: const TextStyle(
            color: AppTheme.textGold,
            fontSize: 12,
            fontWeight: FontWeight.w600,
          ),
          dataTextStyle: const TextStyle(
            color: AppTheme.textSecondary,
            fontSize: 12,
          ),
          columnSpacing: 16,
          horizontalMargin: 14,
          columns: const [
            DataColumn(label: Text('Datum')),
            DataColumn(label: Text('Beginn')),
            DataColumn(label: Text('Ende')),
            DataColumn(label: Text('Stunden'), numeric: true),
            DataColumn(label: Text('Notiz')),
          ],
          rows: _sz.workEntries.map((entry) {
            return DataRow(cells: [
              DataCell(Text(dateFormat.format(entry.date))),
              DataCell(Text(entry.startTime)),
              DataCell(Text(entry.endTime)),
              DataCell(Text(
                entry.hours.toStringAsFixed(1),
                style: const TextStyle(
                    color: AppTheme.textGold, fontWeight: FontWeight.w600),
              )),
              DataCell(Text(
                entry.note ?? '–',
                overflow: TextOverflow.ellipsis,
              )),
            ]);
          }).toList(),
        ),
      ),
    );
  }

  Widget _buildSignaturesRow() {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Expanded(child: _buildAdminSignatureBox()),
        const SizedBox(width: 12),
        Expanded(child: _buildEmployeeSignatureBox()),
      ],
    );
  }

  Widget _buildAdminSignatureBox() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: AppTheme.bgCard,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppTheme.borderGold),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Row(
            children: [
              Icon(Icons.admin_panel_settings_rounded,
                  color: AppTheme.goldPrimary, size: 16),
              SizedBox(width: 6),
              Text(
                'Admin',
                style: TextStyle(
                  color: AppTheme.textGold,
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          if (_sz.adminSignature != null) ...[
            Container(
              height: 100,
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(8),
              ),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(8),
                child: Image.memory(
                  base64Decode(_sz.adminSignature!),
                  fit: BoxFit.contain,
                  width: double.infinity,
                ),
              ),
            ),
            if (_sz.adminSignedAt != null) ...[
              const SizedBox(height: 6),
              Text(
                DateFormat('dd.MM.yyyy HH:mm').format(_sz.adminSignedAt!),
                style: const TextStyle(
                    color: AppTheme.textMuted, fontSize: 10),
              ),
            ],
          ] else ...[
            Container(
              height: 70,
              decoration: BoxDecoration(
                color: AppTheme.bgCardElevated,
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: AppTheme.border),
              ),
              child: const Center(
                child: Text(
                  'Nicht unterschrieben',
                  style: TextStyle(
                      color: AppTheme.textMuted, fontSize: 12),
                ),
              ),
            ),
            const SizedBox(height: 10),
            GoldButton(
              label: 'Jetzt unterschreiben',
              icon: Icons.draw_rounded,
              isLoading: _isSigning,
              onPressed: _isSigning ? null : _signAdmin,
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildEmployeeSignatureBox() {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: AppTheme.bgCard,
        borderRadius: BorderRadius.circular(14),
        border: Border.all(color: AppTheme.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Row(
            children: [
              Icon(Icons.person_rounded,
                  color: AppTheme.textSecondary, size: 16),
              SizedBox(width: 6),
              Text(
                'Mitarbeiter',
                style: TextStyle(
                  color: AppTheme.textSecondary,
                  fontSize: 13,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ],
          ),
          const SizedBox(height: 10),
          if (_sz.employeeSignature != null) ...[
            Container(
              height: 100,
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(8),
              ),
              child: ClipRRect(
                borderRadius: BorderRadius.circular(8),
                child: Image.memory(
                  base64Decode(_sz.employeeSignature!),
                  fit: BoxFit.contain,
                  width: double.infinity,
                ),
              ),
            ),
            if (_sz.employeeSignedAt != null) ...[
              const SizedBox(height: 6),
              Text(
                DateFormat('dd.MM.yyyy HH:mm')
                    .format(_sz.employeeSignedAt!),
                style: const TextStyle(
                    color: AppTheme.textMuted, fontSize: 10),
              ),
            ],
          ] else ...[
            Container(
              height: 70,
              decoration: BoxDecoration(
                color: AppTheme.bgCardElevated,
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: AppTheme.border),
              ),
              child: const Center(
                child: Text(
                  'Ausstehend',
                  style: TextStyle(
                      color: AppTheme.textMuted, fontSize: 12),
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  // Banner removed since generation is automatic on employee side
}
